name: 'Automatic Pull Request'
description: 'Fix issues with AI-generated pull requests, powered by ChatGPT GPT-4'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  openai_api_key:
    description: 'OpenAI api key'
    required: true
  issue_number:
    description: 'Branch name'
    required: true
  issue_title:
    description: 'Issue title'
    required: true
  issue_body:
    description: 'Issue body'
    required: true
  base_branch:
    description: 'Base branch'
    default: 'main'
