name: 'Automatic Pull Request'
description: 'Fix issues with AI-generated pull requests, powered by ChatGPT GPT-4 (AutoPR)'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  base_branch:
    description: 'Base branch'
    default: 'main'
  loading_gif_url:
    description: 'URL of the gif to display while the PR is being generated'
    default: 'https://media0.giphy.com/media/l3nWhI38IWDofyDrW/giphy.gif'
  model:
    description: 'Name of the OpenAI chat model'
    default: 'gpt-4'
  context_limit:
    description: 'Maximum size of the context window to use, varies depending on the model and preference'
    default: '8192'
  min_tokens:
    description: 'Minimum number of tokens to be made available for generation'
    default: '1000'
  max_tokens:
    description: 'Maximum number of tokens to generate'
    default: '2000'
  num_reasks:
    description: 'Number of times to re-ask the model in file exploration and commit generation'
    default: '2'
  agent_id:
    description: 'ID of the brain to use'
    default: 'plan_and_code'
  agent_config:
    description: 'Configuration for the coordinating agent in yaml format'
    default: ''
  target_branch_name_template:
    description: 'Template for the name of the target branch'
    default: 'autopr/{issue_number}'
  temperature:
    description: 'Temperature for the model'
    default: '0.9'
  rail_temperture:
    description: 'Temperature for the guardrails calls'
    default: '0.9'
  overwrite_existing:
    description: 'Whether to overwrite existing branches and pull requests when creating from issues'
    default: 'false'